- name: Configure webserver with ansible
  hosts: webservers
  become: true
  vars: 
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.pem
    conf_file: /etc/nginx/conf.d/default.conf
    servername: localhost
  tasks:
    - name: install nginx
      yum: name=nginx state=latest
        
    - name: create ssl directory
      file: path=/etc/nginx/ssl state=directory
     
    - name: copy TLS key
      copy: src=/root/playbooks/files/nginx.key dest={{key_file}} owner=root mode=0600

    - name: copy TLS certicate
      copy: src=/root/playbooks/files/nginx.crt dest={{cert_file}}

        
    - name: copy nginx config file
      template: src=/root/playbooks/files/nginx.conf.j2 dest={{conf_file}}
      notify: restart nginx
      # - name: enable nginx service
      #command: systemctl enable nginx

    - name: copy index.html
      template: src=/root/playbooks/templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restart
