- name: Configure webserver with ansible
  hosts: webservers2
  become: true
  tasks:
    - name: install nginx prerequires
      yum: name=yum-utils state=latest
    
    - name: copy nginx repo
      copy: src=/root/playbooks/files/nginx.repo dest=/etc/yum.repos.d/nginx.repo
   
    - name: enable nginx repo
      command: yum-config-manager --enable nginx-stable
    
    - name: install nginx
      yum: name=nginx state=latest

    - name: copy nginx config file
      copy: src=/root/playbooks/files/nginx.conf dest=/etc/nginx/conf.d/default.conf
    
    - name: enable nginx service
      command: systemctl enable nginx

    - name: copy index.html
      template: src=/root/playbooks/templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx 
      service: name=nginx state=restarted
